const tarot=[['Der Stern','Hoffnung, Heilung und neue Zuversicht.'],['Die Sonne','Freude, Erfolg und ein klares Ja zum Leben.'],['Die Liebenden','Eine wichtige Entscheidung und echte Verbindung.'],['Der Mond','Vertraue deiner Intuition, auch wenn noch nicht alles sichtbar ist.'],['Die Welt','Ein Zyklus vollendet sich und eine neue Tür öffnet sich.'],['Die Kaiserin','Wachstum, Kreativität und Fülle kommen in Bewegung.'],['Der Magier','Du hast mehr Einfluss auf die Situation, als du denkst.'],['Der Wagen','Entschlossenheit bringt dich deinem Ziel näher.'],['Die Hohepriesterin','Höre auf deine innere Stimme und gib dir Zeit.']];
const zodiac=[['♈','Widder','Mut und Aufbruch'],['♉','Stier','Stabilität und Genuss'],['♊','Zwillinge','Neugier und Austausch'],['♋','Krebs','Gefühl und Nähe'],['♌','Löwe','Selbstvertrauen und Strahlen'],['♍','Jungfrau','Klarheit und Ordnung'],['♎','Waage','Harmonie und Beziehung'],['♏','Skorpion','Tiefe und Veränderung'],['♐','Schütze','Freiheit und Abenteuer'],['♑','Steinbock','Zielstrebigkeit und Aufbau'],['♒','Wassermann','Ideen und Unabhängigkeit'],['♓','Fische','Intuition und Fantasie']];
const answers=['Ja – die Energie ist auf deiner Seite.','Noch nicht – gib der Sache etwas Zeit.','Ja, aber nur wenn du deinem Gefühl vertraust.','Die Antwort liegt näher, als du denkst.','Ein klares Zeichen kommt, wenn du den nächsten Schritt wagst.'];
const modal=document.getElementById('modal'), modalContent=document.getElementById('modalContent');
function openModal(html){modalContent.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.getElementById('closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));

document.querySelectorAll('.oracle-card,.feature').forEach(b=>b.addEventListener('click',()=>runReading(b.dataset.reading)));
function runReading(type){
 if(type==='tarot'){document.getElementById('tarot').scrollIntoView({behavior:'smooth'});return}
 let title='',text='';
 if(type==='love'){title='♡ Liebesorakel';text='Eine ehrliche Begegnung kann näher sein, als du glaubst. Sei offen für ein Gespräch, das mehr verändert, als erwartet.'}
 if(type==='yesno'){title='☼ Ja oder Nein';text=answers[Math.floor(Math.random()*answers.length)]}
 if(type==='daily'){title='☀ Deine Tagesbotschaft';text='Heute geht es darum, nicht alles kontrollieren zu wollen. Eine kleine spontane Entscheidung kann dir eine neue Perspektive schenken.'}
 if(type==='dream'){title='☁ Traumdeutung';text='Träume sind persönlich. Wasser steht oft für Gefühle, Wege für Entscheidungen und Häuser für dein inneres Zuhause. Welche Bilder sind dir besonders im Gedächtnis geblieben?'}
 if(type==='soulmate'){title='💫 Seelenverbindung';text='Eure Verbindung wirkt besonders stark, wenn Vertrauen, Leichtigkeit und ehrliche Kommunikation zusammenkommen. Dein heutiger Impuls: Sprich aus, was du wirklich fühlst.'}
 if(type==='wheel'){title='🎡 Dein Glücksrad';text=['Liebe','Mut','Neuanfang','Reise','Überraschung','Erfolg'][Math.floor(Math.random()*6)]+' – dieses Thema steht heute symbolisch für dich.'}
 openModal(`<span class="eyebrow">DEGAJA ORAKEL</span><h2>${title}</h2><p>${text}</p><button class="primary" onclick="closeModal()">Danke ✨</button>`)
}

document.getElementById('drawBtn').onclick=()=>{const els=[...document.querySelectorAll('.tarot-card')];const picked=[...tarot].sort(()=>Math.random()-.5).slice(0,3);els.forEach((el,i)=>{el.classList.remove('revealed');el.textContent='?';setTimeout(()=>{el.classList.add('revealed');el.innerHTML=`<strong>${picked[i][0]}</strong><br><small>${picked[i][1]}</small>`},350+i*350)});document.getElementById('readingResult').textContent='Deine Legung: Vergangenheit · Gegenwart · Zukunft';};
const zg=document.getElementById('zodiacGrid');zodiac.forEach(z=>{const b=document.createElement('button');b.className='zodiac';b.innerHTML=`<span>${z[0]}</span><strong>${z[1]}</strong><small>${z[2]}</small>`;b.onclick=()=>openModal(`<span class="eyebrow">STERNENBOTSCHAFT</span><h2>${z[0]} ${z[1]}</h2><p>Heute stehen <b>${z[2]}</b> im Mittelpunkt. Nimm dir einen Moment für das, was dir wirklich wichtig ist.</p><button class="primary" onclick="closeModal()">Schließen</button>`);zg.appendChild(b)});
function digitSum(n){return String(n).replace(/\D/g,'').split('').reduce((a,b)=>a+Number(b),0)}
document.getElementById('numberBtn').onclick=()=>{const v=document.getElementById('birthdate').value;if(!v){document.getElementById('numberResult').textContent='Bitte wähle dein Geburtsdatum.';return}let n=digitSum(v);while(n>9&&![11,22,33].includes(n))n=digitSum(n);const meanings={1:'Eigenständigkeit und neue Wege.',2:'Partnerschaft, Balance und Feingefühl.',3:'Kreativität, Ausdruck und Lebensfreude.',4:'Struktur, Sicherheit und Ausdauer.',5:'Freiheit, Bewegung und Veränderung.',6:'Liebe, Verantwortung und Harmonie.',7:'Intuition, Wissen und innere Suche.',8:'Kraft, Erfolg und Selbstvertrauen.',9:'Mitgefühl, Abschluss und Großzügigkeit.',11:'Inspiration und starke Intuition.',22:'Große Visionen und die Kraft, sie umzusetzen.',33:'Mitgefühl, Kreativität und eine besondere Ausstrahlung.'};document.getElementById('numberResult').innerHTML=`<b>Deine Lebenszahl: ${n}</b> · ${meanings[n]}`};

document.getElementById('loginBtn').onclick=()=>openModal(`<span class="eyebrow">DEGAJA KONTO</span><h2>Willkommen zurück.</h2><p>Speichere deine Legungen und erhalte deine persönlichen Tagesbotschaften.</p><input class="modal-input" placeholder="E-Mail-Adresse" type="email"><input class="modal-input" placeholder="Passwort" type="password"><button class="primary" onclick="closeModal()">Anmelden</button><p style="font-size:12px;margin-top:18px">Demo-Anmeldung – noch keine echte Konto- oder Zahlungsfunktion.</p>`);
