const tarot=[['Der Stern','Hoffnung, Heilung und neue Zuversicht.'],['Die Sonne','Freude, Erfolg und ein klares Ja zum Leben.'],['Die Liebenden','Eine wichtige Entscheidung und echte Verbindung.'],['Der Mond','Vertraue deiner Intuition, auch wenn noch nicht alles sichtbar ist.'],['Die Welt','Ein Zyklus vollendet sich und eine neue Tür öffnet sich.'],['Die Kaiserin','Wachstum, Kreativität und Fülle kommen in Bewegung.'],['Der Magier','Du hast mehr Einfluss auf die Situation, als du denkst.'],['Der Wagen','Entschlossenheit bringt dich deinem Ziel näher.'],['Die Hohepriesterin','Höre auf deine innere Stimme und gib dir Zeit.']];
const zodiac=[['♈','Widder','Mut und Aufbruch'],['♉','Stier','Stabilität und Genuss'],['♊','Zwillinge','Neugier und Austausch'],['♋','Krebs','Gefühl und Nähe'],['♌','Löwe','Selbstvertrauen und Strahlen'],['♍','Jungfrau','Klarheit und Ordnung'],['♎','Waage','Harmonie und Beziehung'],['♏','Skorpion','Tiefe und Veränderung'],['♐','Schütze','Freiheit und Abenteuer'],['♑','Steinbock','Zielstrebigkeit und Aufbau'],['♒','Wassermann','Ideen und Unabhängigkeit'],['♓','Fische','Intuition und Fantasie']];
const answers=['Ja – die Energie ist auf deiner Seite.','Noch nicht – gib der Sache etwas Zeit.','Ja, aber nur wenn du deinem Gefühl vertraust.','Die Antwort liegt näher, als du denkst.','Ein klares Zeichen kommt, wenn du den nächsten Schritt wagst.'];
const modal=document.getElementById('modal'), modalContent=document.getElementById('modalContent');
function openModal(html){modalContent.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.getElementById('closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
document.querySelectorAll('.oracle-card,.feature,.topic-row button').forEach(b=>b.addEventListener('click',()=>runReading(b.dataset.reading)));
function runReading(type){if(type==='tarot'){document.getElementById('tarot').scrollIntoView({behavior:'smooth'});return}let title='',text='';if(type==='love'){title='♡ Liebesorakel';text='Eine ehrliche Begegnung kann näher sein, als du glaubst. Sei offen für ein Gespräch, das mehr verändert, als erwartet.'}if(type==='yesno'){title='☼ Ja oder Nein';text=answers[Math.floor(Math.random()*answers.length)]}if(type==='daily'){title='☀ Deine Tagesbotschaft';text='Heute geht es darum, nicht alles kontrollieren zu wollen. Eine kleine spontane Entscheidung kann dir eine neue Perspektive schenken.'}if(type==='dream'){title='☁ Traumdeutung';text='Träume sind persönlich. Wasser steht oft für Gefühle, Wege für Entscheidungen und Häuser für dein inneres Zuhause.'}if(type==='soulmate'){title='💫 Seelenverbindung';text='Eure Verbindung wirkt besonders stark, wenn Vertrauen, Leichtigkeit und ehrliche Kommunikation zusammenkommen.'}if(type==='wheel'){title='🎡 Dein Glücksrad';text=['Liebe','Mut','Neuanfang','Reise','Überraschung','Erfolg'][Math.floor(Math.random()*6)]+' – dieses Thema steht heute symbolisch für dich.'}if(type==='future'){title='🔮 Zukunft';text='Vor dir liegt eine Phase, in der Geduld und ein mutiger nächster Schritt zusammengehören.'}if(type==='money'){title='💰 Geld';text='Ordnung und ein klarer Plan können heute wichtiger sein als eine schnelle Entscheidung.'}if(type==='career'){title='💼 Beruf';text='Eine Gelegenheit kann sich öffnen, wenn du deine Fähigkeiten sichtbarer machst.'}if(type==='general'){title='⭐ Allgemein';text='Nimm dir heute Zeit für das, was dir Energie gibt – nicht nur für das, was Aufmerksamkeit verlangt.'}openModal(`<span class="eyebrow">DEGAJA ORAKEL</span><h2>${title}</h2><p>${text}</p><button class="primary" onclick="closeModal()">Danke ✨</button>`)}

const zg=document.getElementById('zodiacGrid');if(zg)zodiac.forEach(z=>{const b=document.createElement('button');b.className='zodiac';b.innerHTML=`<span>${z[0]}</span><strong>${z[1]}</strong><small>${z[2]}</small>`;b.onclick=()=>openModal(`<span class="eyebrow">STERNENBOTSCHAFT</span><h2>${z[0]} ${z[1]}</h2><p>Heute stehen <b>${z[2]}</b> im Mittelpunkt. Nimm dir einen Moment für das, was dir wirklich wichtig ist.</p><button class="primary" onclick="closeModal()">Schließen</button>`);zg.appendChild(b)});
function digitSum(n){return String(n).replace(/\D/g,'').split('').reduce((a,b)=>a+Number(b),0)}
const numberBtn=document.getElementById('numberBtn');if(numberBtn)numberBtn.onclick=()=>{const v=document.getElementById('birthdate').value;if(!v){document.getElementById('numberResult').textContent='Bitte wähle dein Geburtsdatum.';return}let n=digitSum(v);while(n>9&&![11,22,33].includes(n))n=digitSum(n);const meanings={1:'Eigenständigkeit und neue Wege.',2:'Partnerschaft, Balance und Feingefühl.',3:'Kreativität, Ausdruck und Lebensfreude.',4:'Struktur, Sicherheit und Ausdauer.',5:'Freiheit, Bewegung und Veränderung.',6:'Liebe, Verantwortung und Harmonie.',7:'Intuition, Wissen und innere Suche.',8:'Kraft, Erfolg und Selbstvertrauen.',9:'Mitgefühl, Abschluss und Großzügigkeit.',11:'Inspiration und starke Intuition.',22:'Große Visionen und die Kraft, sie umzusetzen.',33:'Mitgefühl, Kreativität und eine besondere Ausstrahlung.'};document.getElementById('numberResult').innerHTML=`<b>Deine Lebenszahl: ${n}</b> · ${meanings[n]}`};
const loginBtn=document.getElementById('loginBtn');if(loginBtn)loginBtn.onclick=()=>openModal(`<span class="eyebrow">DEGAJA KONTO</span><h2>Willkommen zurück.</h2><p>Speichere deine Legungen und erhalte deine persönlichen Tagesbotschaften.</p><input class="modal-input" placeholder="E-Mail-Adresse" type="email"><input class="modal-input" placeholder="Passwort" type="password"><button class="primary" onclick="closeModal()">Anmelden</button><p style="font-size:12px;margin-top:18px">Demo-Anmeldung – noch keine echte Konto- oder Zahlungsfunktion.</p>`);

/* Live-Beratung: checkout-ready demo flow. Real payment/chat backend comes next. */
const livePlans={10:{duration:'10 Minuten',price:'12 €',note:'Kurze persönliche Frage'},20:{duration:'20 Minuten',price:'24 €',note:'Vertiefte Beratung'},30:{duration:'30 Minuten',price:'35 €',note:'Ausführliche Beratung'},60:{duration:'60 Minuten',price:'60 €',note:'Intensive persönliche Beratung'},180:{duration:'3 Stunden',price:'120 €',note:'Spezialberatung für komplexe oder besondere Anliegen'}};
document.querySelectorAll('.plan[data-live]').forEach(btn=>btn.addEventListener('click',()=>{const p=livePlans[btn.dataset.live];openModal(`<span class="eyebrow">DEGAJA LIVE-BERATUNG</span><h2>${p.duration} · ${p.price}</h2><p><b>${p.note}</b></p><p>Wähle „Beratung anfragen“, um einen verfügbaren DEGAJA-Berater zu finden. Der eigentliche Zahlungs- und Live-Chat-Service wird in der nächsten technischen Phase angebunden.</p><button class="primary" onclick="requestLive('${p.duration}','${p.price}')">💬 Beratung anfragen</button>`)}));
function requestLive(duration,price){openModal(`<span class="eyebrow">ANFRAGE ERSTELLT</span><h2>Wir suchen einen Berater.</h2><p>Deine Auswahl: <b>${duration}</b> für <b>${price}</b>.</p><p>In der produktiven Version folgt hier der sichere Checkout. Danach wird der Live-Chat automatisch freigeschaltet.</p><button class="primary" onclick="closeModal()">Zurück zu DEGAJA</button>`)}

/* DEGAJA SHOP – frontend cart and personalisation demo */
const shopProducts=[
{id:'fasuche',category:'glueck',name:'PAPULI FASUCHE',subtitle:'Tarot Luck Cream',price:39.90,tag:'GLÜCK & SCHUTZ',personal:true,description:'Ein luxuriöses Tarot-inspiriertes Pflegeprodukt als symbolisches Ritual für Glück, positive Energie und persönliche Intention.'},
{id:'tarot-deck',category:'tarot',name:'DEGAJA Tarot Deck',subtitle:'Premium Edition',price:29.90,tag:'TAROT',personal:false,description:'Ein elegantes Tarot-Deck für deine täglichen Legungen und persönlichen Reflexionsmomente.'},
{id:'zodiac-gift',category:'persoenlich',name:'Mein Sternzeichen',subtitle:'Personalisiertes Geschenk',price:34.90,tag:'PERSÖNLICH',personal:true,description:'Ein persönliches DEGAJA Geschenk mit deinem Namen und Sternzeichen – ideal für dich oder einen besonderen Menschen.'},
{id:'lucky-box',category:'geschenke',name:'DEGAJA Glücksbox',subtitle:'Love · Luck · Light',price:49.90,tag:'GESCHENK',personal:true,description:'Eine kuratierte Geschenkbox rund um Liebe, Glück und Neubeginn. Personalisierbar mit einer persönlichen Botschaft.'},
{id:'zodiac-charm',category:'persoenlich',name:'Zodiac Charm',subtitle:'Dein Sternzeichen',price:24.90,tag:'SCHMUCK',personal:true,description:'Ein dezentes Sternzeichen-Schmuckstück mit persönlicher Auswahl.'},
{id:'ritual-candle',category:'glueck',name:'DEGAJA Ritual Candle',subtitle:'New Beginning',price:19.90,tag:'RITUAL',personal:false,description:'Eine stilvolle Duftkerze für einen bewussten Moment, eine neue Intention oder einen persönlichen Neubeginn.'}
];
let cart=JSON.parse(localStorage.getItem('degajaCart')||'[]');
const shopGrid=document.getElementById('shopGrid');
function escapeHtml(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderProductVisual(p){if(p.id==='fasuche')return '<div class="product-visual"><div class="cream-jar">PAPULI<br>FASUCHE<small>TAROT LUCK CREAM</small></div></div>';return `<div class="product-visual"><div style="font-size:58px;color:#c99a4a">${p.category==='tarot'?'🃏':p.category==='geschenke'?'🎁':p.category==='persoenlich'?'✦':'☀'}</div></div>`}
function renderShop(category='all'){if(!shopGrid)return;const list=category==='all'?shopProducts:shopProducts.filter(p=>p.category===category);shopGrid.innerHTML=list.map(p=>`<article class="product-card"><button class="product-image-button" data-product="${p.id}" aria-label="${escapeHtml(p.name)} ansehen">${renderProductVisual(p)}</button><div class="product-body"><span class="product-tag">${p.tag}</span><h3>${p.name}</h3><p><b>${p.subtitle}</b><br>${p.description}</p><div class="product-bottom"><span class="product-price">${p.price.toFixed(2).replace('.',',')} €</span><button class="primary" data-product="${p.id}">${p.personal?'Personalisieren':'Ansehen'}</button></div>${p.personal?'<div class="product-personal">✦ Personalisierbar</div>':''}</div></article>`).join('');shopGrid.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.product)))}
function openProduct(id){const p=shopProducts.find(x=>x.id===id);if(!p)return;openModal(`<div class="shop-product-modal"><span class="eyebrow">DEGAJA SHOP · ${p.tag}</span><h2>${p.name}</h2><p><b>${p.subtitle}</b></p><div class="personal-preview">${p.id==='fasuche'?'<div class="cream-jar mini-jar">PAPULI<br>FASUCHE<small>TAROT LUCK CREAM</small></div>':'<span style="font-size:55px;color:#c99a4a">✦</span>'}</div><p>${p.description}</p>${p.personal?`<div class="personal-form"><label>Name</label><input id="personalName" placeholder="Dein Name"><label>Sternzeichen</label><input id="personalZodiac" placeholder="z. B. Löwe"><label>Geburtsdatum</label><input id="personalBirth" type="date"><label>Persönliche Botschaft</label><textarea id="personalMessage" placeholder="Deine persönliche Botschaft oder Widmung"></textarea></div>`:''}<button class="primary" onclick="addToCart('${p.id}')">🛒 In den Warenkorb · ${p.price.toFixed(2).replace('.',',')} €</button><p style="font-size:11px;margin-top:14px">Demo-Shop: Der echte Zahlungs- und Versandprozess wird später mit einem Commerce-/Payment-Anbieter verbunden.</p></div>`)}
function addToCart(id){const p=shopProducts.find(x=>x.id===id);if(!p)return;const item={id:p.id,name:p.name,price:p.price,personal:p.personal,custom:p.personal?{name:document.getElementById('personalName')?.value||'',zodiac:document.getElementById('personalZodiac')?.value||'',birth:document.getElementById('personalBirth')?.value||'',message:document.getElementById('personalMessage')?.value||''}:null};cart.push(item);saveCart();closeModal();openCart();}
function saveCart(){localStorage.setItem('degajaCart',JSON.stringify(cart));const c=document.getElementById('cartCount');if(c)c.textContent=cart.length}
function removeCart(index){cart.splice(index,1);saveCart();openCart()}
function openCart(){const total=cart.reduce((s,x)=>s+x.price,0);const items=cart.length?cart.map((x,i)=>`<div class="cart-item"><div><b>${escapeHtml(x.name)}</b>${x.custom?.name?`<small>Für: ${escapeHtml(x.custom.name)}${x.custom.zodiac?' · '+escapeHtml(x.custom.zodiac):''}</small>`:''}</div><div><b>${x.price.toFixed(2).replace('.',',')} €</b><button class="close" style="position:static;font-size:20px;margin-left:8px" onclick="removeCart(${i})">×</button></div></div>`).join(''):'<div class="empty-cart">Dein Warenkorb ist noch leer.</div>';openModal(`<span class="eyebrow">DEGAJA SHOP</span><h2>Dein Warenkorb</h2>${items}<div class="cart-total"><span>Gesamt</span><span>${total.toFixed(2).replace('.',',')} €</span></div>${cart.length?'<button class="primary" onclick="checkoutDemo()">Zur Kasse</button>':''}`)}
function checkoutDemo(){openModal(`<span class="eyebrow">DEGAJA CHECKOUT</span><h2>Deine Bestellung</h2><p>Fast geschafft. Gib deine Kontaktdaten ein. Der echte Zahlungsanbieter wird in der nächsten Commerce-Phase angebunden.</p><input class="checkout-field" placeholder="Vorname & Nachname"><input class="checkout-field" placeholder="E-Mail-Adresse" type="email"><input class="checkout-field" placeholder="Lieferadresse"><button class="primary" onclick="completeDemoOrder()">Bestellung vorbereiten</button><p style="font-size:11px;margin-top:14px">Noch keine echte Zahlung – dies ist eine sichere Frontend-Demo.</p>`)}
function completeDemoOrder(){cart=[];saveCart();openModal(`<span class="eyebrow">DEGAJA SHOP</span><h2>Vielen Dank ✨</h2><p>Deine Bestellung wurde als Demo vorbereitet. Sobald der echte Checkout angeschlossen ist, wird die Zahlung und Lieferung hier vollständig abgewickelt.</p><button class="primary" onclick="closeModal()">Weiter shoppen</button>`)}
if(shopGrid)renderShop();
document.querySelectorAll('.shop-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.shop-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderShop(b.dataset.category)}));
const cartBtn=document.getElementById('cartBtn');if(cartBtn)cartBtn.onclick=openCart;saveCart();
